---
- name: "F5 Simulation: Manual Input Member Manager"
  hosts: all
  become: yes
  
  tasks:
    - name: "Cek apakah Member ada di HAProxy"
      shell: |
        echo "show stat" | socat stdio /run/haproxy/admin.sock | grep "{{ v_member_name }}"
      register: check_member
      ignore_errors: yes

    - name: "Gagal jika Member tidak ditemukan"
      fail:
        msg: "Error: Member '{{ v_member_name }}' tidak ditemukan di HAProxy!"
      when: check_member.rc != 0

    - name: "Update Weight untuk {{ v_member_name }}"
      shell: |
        echo "set server site_distribution/{{ v_member_name }} weight {{ v_weight }}" | socat stdio /run/haproxy/admin.sock
      when: check_member.rc == 0

    - name: "Konfirmasi Hasil"
      debug:
        msg: "Berhasil! Member {{ v_member_name }} sekarang memiliki Weight {{ v_weight }}"
