---
- name: "Simulasi F5: Manage Pool Member Weight"
  hosts: all
  become: yes
  vars:
    # Nama backend dan server harus SAMA dengan yang ada di /etc/haproxy/haproxy.cfg
    target_backend: "my_app_pool"
    server_name: "server-A"
    new_weight: 80

  tasks:
    - name: "Ubah Weight Member secara Runtime"
      community.general.haproxy:
        socket: /run/haproxy/admin.sock
        backend: "{{ target_backend }}"
        host: "{{ server_name }}"
        weight: "{{ new_weight }}"
        state: enabled
      register: result

    - name: "Konfirmasi Perubahan"
      debug:
        msg: "Status: {{ result.msg }} | Weight {{ server_name }} sekarang: {{ new_weight }}"