---
- name: "Failover: Paksa 100% Trafik ke Site A (Native Shell)"
  hosts: all
  become: yes
  
  tasks:
    - name: "Set Site A ke Weight 100"
      shell: |
        echo "set server site_distribution/Site-A-Jagakarsa weight 100" | socat stdio /run/haproxy/admin.sock
      register: result_a

    - name: "Set Site B ke Weight 0 (Drain)"
      shell: |
        echo "set server site_distribution/Site-B-Jogja weight 0" | socat stdio /run/haproxy/admin.sock
      register: result_b

    - name: "Tampilkan Hasil Konfirmasi"
      debug:
        msg: "Berhasil memindahkan trafik ke Site A Jagakarsa!"
