---
- name: "Failover: Paksa 100% Trafik ke Site A Jagakarsa"
  hosts: all
  become: yes
  
  tasks:
    - name: "Matikan Site Jogja (Set Maintenance Mode)"
      shell: |
        echo "set server site_distribution/Site-B-Jogja state maint" | socat stdio /run/haproxy/admin.sock

    - name: "Pastikan Site Jagakarsa Aktif (Set Ready Mode)"
      shell: |
        echo "set server site_distribution/Site-A-Jagakarsa state ready" | socat stdio /run/haproxy/admin.sock
        echo "set server site_distribution/Site-A-Jagakarsa weight 100" | socat stdio /run/haproxy/admin.sock
