---
- name: "Cek Koneksi, IP, dan OS Target"
  hosts: all
  gather_facts: yes  # Ini otomatis akan mengambil data IP dan OS

  tasks:
    - name: "Tampilkan Info Hostname dan OS"
      debug:
        msg: 
          - "Hostname: {{ ansible_hostname }}"
          - "Sistem Operasi: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Arsitektur: {{ ansible_architecture }}"

    - name: "Tampilkan Alamat IP Host"
      debug:
        msg: "Alamat IP di Server ini adalah: {{ ansible_default_ipv4.address }}"
